image:
- Ubuntu
- Visual Studio 2017
build: off

for:
 - 
    matrix:
     only:
      - image: Ubuntu

    build_script:
    - echo Compiling with Ubuntu
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
