image:
- Ubuntu
- Visual Studio 2017
build: off

for:
 - 
    matrix:
     only:
      - image: Ubuntu
    before_script:
    - sudo apt-get -y install qt5-default
    
    build_script:
    - echo Compiling with Ubuntu
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
