image:
 - Ubuntu

build: 
 - sh: echo "default script"

for:
 -
    matrix:
            only:
                    - image: Ubuntu
            build_script:
                    - sh: echo "build for ubuntu"
